[package]
name = "nenu-thesis"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Virgil <virgiling7@gmail.com>"]
license = "MIT-0"
description = "A thesis template for NENU students"

[template]
path = "template"
entrypoint = "thesis.typ"
